### ISSUE TITLE
[🐛 Bug]: wdio8 starter project is not working with typescript

### ISSUE THREAD

**Issue by Badisi** [webdriverio/create-wdio#306]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.9

### Environment

- **OS Name**: macOS Monterey (version 12.6.1)
- **System Model Name**: MacBook Pro (16-inch, 2019)
- **npm**: 7.6.3
- **Node.js**: 13.14.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
  maxInstances: 5,
  browserName: 'chrome',
  acceptInsecureCerts: true
}]
```

### What happened?

Starting a new wdio project with `typescript` actually results in multiple errors.

I know that there is another opened issue that seems related (#9334) but I needed a plain new issue to report all I've found and the corresponding fixes.

*NB: I have no idea where to fix that in the code, nor time to submit a PR, so I let you guys decide what to do ;-)*

---

After following the steps described in the **How to reproduce the bug** section and running the tests, here is what I have encountered:

### Issue 1: Unexpected token 'export'
```sh
/Users/Badisi/Workspace/test-wdio/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module.m._compile (/Users/jpti/Workspace/test-wdio/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jpti/Workspace/test-wdio/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
```

#### Solution
This can be resolved by setting `type:module` in the `package.json`:
```json
{
  "type": "module"
}
```

### Issue2: Cannot find module ... imported from ...
```sh
@wdio/runner: Error: Cannot find module '/Users/Badisi/Workspace/test-wdio/test/pageobjects/login.page' imported from /Users/Badisi/Workspace/test-wdio/test/specs/example.e2e.ts
[0-0]     at finalizeResolution (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
[0-0]     at moduleResolve (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
[0-0]     at Object.defaultResolve (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[0-0]     at /Users/Badisi/Workspace/test-wdio/node_modules/ts-node/src/esm.ts:218:35
[0-0]     at entrypointFallback (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/src/esm.ts:168:34)
[0-0]     at /Users/Badisi/Workspace/test-wdio/node_modules/ts-node/src/esm.ts:217:14
[0-0]     at addShortCircuitFlag (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/src/esm.ts:409:21)
[0-0]     at resolve (/Users/Badisi/Workspace/test-wdio/node_modules/ts-node/src/esm.ts:197:12)
[0-0]     at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
[0-0]     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
```
#### Solution
Looks like the issue comes from `ts-node` but instead comes from `typescript`.
Having set `type:module` in `package.json` now requires the relative import paths to have full extensions (see the [blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#type-in-package-json-and-new-extensions) from Microsoft for more details).
So the solution is to put a `.js` extension at the end of these imports:
```ts
// test/pageobjects/login.page.ts
// test/pageobjects/login.page.ts
import Page from './page.js';

// test/specs/example.e2e.ts
import LoginPage from '../pageobjects/login.page.js';
import SecurePage from '../pageobjects/secure.page.js';
```

And now everything is working as expected!

### How to reproduce the bug.

1. Create a new project using : `npm init wdio@latest .`
2. Use the following answers:
   - Where should your tests be launched? -> **local**
   - Where is your automation backend located? -> **On my local machine**
   - Which framework do you want to use? -> **Jasmine**
   - Do you want to use a compiler? -> **TypeScript**
   - Do you want WebdriverIO to autogenerate some test files? -> **Yes**
   - Where should these files be located? -> **accept defaults**
   - Do you want to use page objects -> **Yes**
   - Where are your page objects located? -> **accept defaults**
   - Which reporter do you want to use? -> **spec**
   - Do you want to add a plugin to your test setup? -> **none**
   - Do you want to add a service to your test setup? -> **chromedriver**
   - What is the base url? -> **accept defaults**
   - Do you want me to run `npm install` -> **Yes**
3. Start the tests with : `npm run wdio`

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Badisi** [comment]
@christian-bromann, I can confirm this is working in `create-wdio@8.2.0`.

As usual, thanks a lot for your quickness and efficiency ❤️

**Comment by anthony-bernardo** [comment]
still not working, i'm using 

```
npm init wdio@latest .
```

**Comment by christian-bromann** [comment]
> still not working

This is not very helpful to understand the error. Please provide more information on which error you see, which answer you provided etc.

**Comment by cloud0259** [comment]
I still have the problem too.
I used the command "ng e2e" and I also used the command "npm init wdio@latest ." 
The error "SyntaxError: Unexpected token 'export'" always appears when running "npm run wdio" and "wdio run ./wdio.conf.ts".

I am on windows with wdio 8.3.10

**Comment by Badisi** [comment]
I did exactly the same as I originally described in the "**How to reproduce the bug**." section of this issue and everything is still working for me.

Can you guys please provide more details on what you are doing different ?

---

Also, I mentioned that the error "Unexpected token export" could be resolved by setting `type: module` in `package.json`. @cloud0259, did wdio generated that property for you ? and if not have you tried setting it yourself ?

**Comment by cloud0259** [comment]
@Badisi 
where can i add this line?

**Comment by allinprunes** [comment]
@christian-bromann Thanks a lot for this!  👏 👏 👏

**Comment by alcon678** [comment]
I'm still facing the same issue in a brand new ionic project
System MacOS 14.3 

repro steps:
```
ionic start
? Framework: Angular
? Project name: wdio-test
? Starter template: blank
NgModules

cd wdio-test
npm init wdio@latest .

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "wdio-test" was detected at "/Users/user/wdio-test", correct? Yes
? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? Chrome
? Which framework do you want to use? Cucumber with Serenity/JS (https://serenity-js.org/)
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Do you want WebdriverIO to autogenerate some test files? Yes
? What should be the location of your feature files? /Users/user/wdio-test/features/**/*.feature
? What should be the location of your step definitions? /Users/user/wdio-test/features/step-definitions/steps.ts
? What should be the location of your Serenity/JS Screenplay Pattern library? /Users/user/wdio-test/serenity
? Which reporter do you want to use? spec, allure, cucumber-json
? Do you want to add a plugin to your test setup? wait-for: utilities that provide functionalities to wait for certain conditions till a defined task is complete.
   > https://www.npmjs.com/package/wdio-wait-for, angular-component-harnesses: support for Angular component test harnesses
   > https://www.npmjs.com/package/@badisi/wdio-harness, Testing Library: utilities that encourage good testing practices laid down by dom-testing-library.
   > https://testing-library.com/docs/webdriverio-testing-library/intro
? Do you want to add a service to your test setup? 
? What is the base url? http://localhost
? Do you want me to run `npm install` Yes

➜ npm run serenity
> wdio-test@0.0.1 serenity
> failsafe serenity:update serenity:clean wdio serenity:report

[serenity:update] 
[serenity:update] > wdio-test@0.0.1 serenity:update
[serenity:update] > serenity-bdd update
[serenity:update] 
[serenity:update] Looks like you need the latest Serenity BDD CLI jar. Let me download it for you...
[serenity:update] Downloading https://repo1.maven.org/maven2/net/serenity-bdd/serenity-cli/4.0.48/serenity-cli-4.0.48.jar to node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-4.0.48.jar.download
[serenity:update] 
[serenity:update] Verifying checksums...
[serenity:update] Downloaded node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-4.0.48.jar
[failsafe] Script 'serenity:update' exited with code 0
[serenity:clean] 
[serenity:clean] > wdio-test@0.0.1 serenity:clean
[serenity:clean] > rimraf target
[serenity:clean] 
[failsafe] Script 'serenity:clean' exited with code 0
[wdio] 
[wdio] > wdio-test@0.0.1 wdio
[wdio] > wdio run ./wdio.conf.ts
[wdio] 
[wdio] 2024-02-11T01:11:48.159Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/user/wdio-test/wdio.conf.ts: Unexpected token 'export'
[wdio] /Users/user/wdio-test/wdio.conf.ts:1
[wdio] export const config = {
[wdio] ^^^^^^
[wdio] 
[wdio] SyntaxError: Unexpected token 'export'
[wdio]     at internalCompileFunction (node:internal/vm:77:18)
[wdio]     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
[wdio]     at Module._compile (node:internal/modules/cjs/loader:1340:27)
[wdio]     at Module.m._compile (/Users/user/wdio-test/node_modules/ts-node/src/index.ts:1618:23)
[wdio]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[wdio]     at Object.require.extensions.<computed> [as .ts] (/Users/user/wdio-test/node_modules/ts-node/src/index.ts:1621:12)
[wdio]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[wdio]     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
[wdio]     at cjsLoader (node:internal/modules/esm/translators:356:17)
[wdio]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
[wdio]     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
[wdio]     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
[wdio]     at async ConfigParser.addConfigFile (file:///Users/user/wdio-test/node_modules/@wdio/config/build/node/ConfigParser.js:86:36)
[wdio]     at async ConfigParser.initialize (file:///Users/user/wdio-test/node_modules/@wdio/config/build/node/ConfigParser.js:48:13)
[wdio]     at async Launcher.run (file:///Users/user/wdio-test/node_modules/@wdio/cli/build/launcher.js:41:9)
[failsafe] Script 'wdio' exited with code 1
[serenity:report] 
[serenity:report] > wdio-test@0.0.1 serenity:report
[serenity:report] > serenity-bdd run
[serenity:report] 
[serenity:report] Spawning: /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home/bin/java -DLOG_LEVEL=warn -Dlogback.configurationFile=/Users/user/wdio-test/node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -Dserenity.compress.filenames=true -Dserenity.features.directory=Path(value=features) -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-4.0.48.jar --destination target/site/serenity --features Path(value=features) --source target/site/serenity --project wdio-test
[serenity:report] -------------------------------
[serenity:report] SERENITY COMMAND LINE INTERFACE
[serenity:report] -------------------------------
[serenity:report] Loading test outcomes from target/site/serenity
[serenity:report] Writing aggregated report to target/site/serenity
[serenity:report] 
[failsafe] Script 'serenity:report' exited with code 0
[failsafe] Failed with exit code 1 due to failing script: 'wdio'
```

Adding type module in packaje.json leads to the other exact error
```
[wdio] [0-0] 2024-02-11T01:19:06.976Z ERROR @wdio/runner: Error: Cannot find module '/Users/user/wdio-test/serenity/todo-list-app/TodoList' imported from /Users/user/wdio-test/features/step-definitions/steps.ts
[wdio] [0-0]     at finalizeResolution (/Users/user/wdio-test/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
[wdio] [0-0]     at moduleResolve (/Users/user/wdio-test/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
[wdio] [0-0]     at Object.defaultResolve (/Users/user/wdio-test/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[wdio] [0-0]     at /Users/user/wdio-test/node_modules/ts-node/src/esm.ts:218:35
[wdio] [0-0]     at entrypointFallback (/Users/user/wdio-test/node_modules/ts-node/src/esm.ts:168:34)
[wdio] [0-0]     at /Users/user/wdio-test/node_modules/ts-node/src/esm.ts:217:14
[wdio] [0-0]     at addShortCircuitFlag (/Users/user/wdio-test/node_modules/ts-node/src/esm.ts:409:21)
[wdio] [0-0]     at resolve (/Users/user/wdio-test/node_modules/ts-node/src/esm.ts:197:12)
[wdio] [0-0]     at nextResolve (node:internal/modules/esm/hooks:865:28)
[wdio] [0-0]     at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
[wdio] [0-0]  Error:  Cannot find module '/Users/user/wdio-test/serenity/todo-list-app/TodoList' imported from /Users/whocares/wdio-test/features/step-definitions/steps.ts

```

**Comment by Badisi** [comment]
There were also a solution provided for the « cannot find module imported from ». Did it worked too ? (ie. renaming the imports)

If that so, it means it is the ionic starter that needs to be refactored, not a wdio issue

**Comment by alcon678** [comment]
it didn't because cucumberjs-json
```
[wdio] [0-0] 2024-02-11T12:11:47.286Z ERROR @wdio/runner: TypeError: Cannot read properties of undefined (reading 'elements')
[wdio] [0-0]     at CucumberJsJsonReporter.getCurrentScenario (file:///Users/whocares/wdio-test/node_modules/wdio-cucumberjs-json-reporter/src/index.ts:308:36)
[wdio] [0-0]     at CucumberJsJsonReporter.addStepData (file:///Users/whocares/wdio-test/node_modules/wdio-cucumberjs-json-reporter/src/index.ts:326:14)
[wdio] [0-0]     at CucumberJsJsonReporter.onTestStart (file:///Users/whocares/wdio-test/node_modules/wdio-cucumberjs-json-reporter/src/index.ts:152:14)
[wdio] [0-0]     at CucumberJsJsonReporter.<anonymous> (file:///Users/whocares/wdio-test/node_modules/@wdio/reporter/build/index.js:100:18)
[wdio] [0-0]     at CucumberJsJsonReporter.emit (node:events:518:28)
[wdio] [0-0]     at CucumberJsJsonReporter.emit (node:domain:488:12)
[wdio] [0-0]     at file:///Users/whocares/wdio-test/node_modules/@wdio/runner/build/reporter.js:47:56
[wdio] [0-0]     at Array.forEach (<anonymous>)
[wdio] [0-0]     at BaseReporter.emit (file:///Users/whocares/wdio-test/node_modules/@wdio/runner/build/reporter.js:47:25)
[wdio] [0-0]     at WebdriverIONotifier.onSceneStarts (file:///Users/whocares/wdio-test/node_modules/@serenity-js/webdriverio/src/adapter/WebdriverIONotifier.ts:157:23)
[wdio] [0-0]     at MatchesObjectsWithCommonPrototype.execute (/Users/whocares/wdio-test/node_modules/tiny-types/src/pattern-matching/rules/MatcherRule.ts:13:21)
[wdio] [0-0]     at ObjectMatcher.else (/Users/whocares/wdio-test/node_modules/tiny-types/src/pattern-matching/PatternMatcher.ts:18:71)
[wdio] [0-0]     at WebdriverIONotifier.notifyOf (file:///Users/whocares/wdio-test/node_modules/@serenity-js/webdriverio/src/adapter/WebdriverIONotifier.ts:92:18)
[wdio] [0-0]     at /Users/whocares/wdio-test/node_modules/@serenity-js/core/src/stage/StageManager.ts:29:59
[wdio] [0-0]     at Array.forEach (<anonymous>)
[wdio] [0-0]     at StageManager.notifyOf (/Users/whocares/wdio-test/node_modules/@serenity-js/core/src/stage/StageManager.ts:29:26)
[wdio] [0-0]  Error:  Cannot read properties of undefined (reading 'elements')
```

I have removed and it works but is there any solution to avoid adding the js extension to every file import?
Thanks

**Comment by christian-bromann** [comment]
> I have removed and it works but is there any solution to avoid adding the js extension to every file import?

This is required when running within ESM context. Using `import` statements run cross platform, therefore also in the browser and it would be a bad idea performance wise to try different file extensions to load. That is why it is required. Unless your aren't using a compiler there is no way to avoid this.
