### ISSUE TITLE
Couldn't initialise "@wdio/cucumber-framework"

### ISSUE THREAD

**Issue by restagner** [webdriverio/create-wdio#68]
I'm new to WebDriverIO.  I followed the get started instructions at https://webdriver.io/docs/gettingstarted.  However when I execute `npm run wdio` I see the following error message

```
[0-0] 2022-01-07T01:32:53.026Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "@wdio/cucumber-framework".
[0-0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/formatter/helpers/event_data_collector' is not defined by "exports" in /Users/stagr005/workspace/wdio-sample/node_modules/@cucumber/cucumber/package.json
[0-0]     at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
[0-0]     at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
[0-0]     at resolveExports (internal/modules/cjs/loader.js:450:36)
[0-0]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
[0-0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
[0-0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0-0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0-0]     at require (internal/modules/cjs/helpers.js:88:18)
[0-0]     at Object.<anonymous> (/Users/stagr005/workspace/wdio-sample/node_modules/@wdio/cucumber-framework/build/index.js:49:48)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1076:30)
[0-0]     at safeRequire (/Users/stagr005/workspace/wdio-sample/node_modules/@wdio/utils/build/utils.js:187:15)
[0-0]     at initialisePlugin (/Users/stagr005/workspace/wdio-sample/node_modules/@wdio/utils/build/initialisePlugin.js:30:50)
[0-0]     at Runner.run (/Users/stagr005/workspace/wdio-sample/node_modules/@wdio/runner/build/index.js:82:56)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0-0] FAILED
```

I'm not sure how to resolve this.  Any assistance would be appreciated

**Comment by christian-bromann** [comment]
@restagner can you try with latest version again? This error was not reported anywhere else.

**Comment by christian-bromann** [comment]
Closing due to inactivity.

**Comment by Spiral-Galaxy-28948** [comment]
Morning @christian-bromann, we're starting to implement webdriverIO, but also getting this error:

[0-0] 2022-07-26T08:41:50.411Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "@wdio/cucumber-framework".
[0-0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/formatter/helpers/event_data_collector' is not defined by "exports" in H:\git-projects\test-rlggtc-wdio_cucumber\node_modules\@cucumber\cucumber\package.json
[0-0]     at applyExports (internal/modules/cjs/loader.js:490:9)
[0-0]     at resolveExports (internal/modules/cjs/loader.js:506:23)
[0-0]     at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
[0-0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
[0-0]     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
[0-0]     at Module.require (internal/modules/cjs/loader.js:1025:19)
[0-0]     at require (internal/modules/cjs/helpers.js:72:18)
[0-0]     at Object.<anonymous> (H:\git-projects\test-rlggtc-wdio_cucumber\node_modules\@wdio\cucumber-framework\build\index.js:54:48)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[0-0]     at safeRequire (H:\git-projects\test-rlggtc-wdio_cucumber\node_modules\@wdio\utils\build\utils.js:192:15)
[0-0]     at initialisePlugin (H:\git-projects\test-rlggtc-wdio_cucumber\node_modules\@wdio\utils\build\initialisePlugin.js:30:50)
[0-0]     at Runner.run (H:\git-projects\test-rlggtc-wdio_cucumber\node_modules\@wdio\runner\build\index.js:82:56)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)

We're using wdio/cucumber-framework 7.20.3 and wdio/local-runner 7.20.2 on node 12.18.3. I was hoping it was just me, but my colleagues are getting it also.

Any suggestions on how to resolve it? Cheers.

**Comment by christian-bromann** [comment]
@Spiral-Galaxy-28948 can you provide a reproducible example?

**Comment by Spiral-Galaxy-28948** [comment]
Here you go @christian-bromann https://github.com/Spiral-Galaxy-28948/wdio-cucumber.git

**Comment by christian-bromann** [comment]
@Spiral-Galaxy-28948 this example passes for me without any errors.

**Comment by Spiral-Galaxy-28948** [comment]
@christian-bromann, I thought you might say that. It passes on my personal machine, but not on my work one (cucumber tests worked when I was researching the tool set). Can you think of any environmental reasons - we use virtual windows 10 machines - why this error could occur? As far as I can tell from digging into the data_collector package the export is defined.

**Comment by christian-bromann** [comment]
No idea sorry.

**Comment by Spiral-Galaxy-28948** [comment]
Cool. Cheers for checking it out.
